### ISSUE TITLE
Escape pattern letting users into folder of user directories

### ISSUE THREAD

**Issue by zxz41** [Earu/EARU.IO#5]
For some reason `\..` let people escape into the users directory. Haven't tested if fiddling with post requests can let users upload files etc there.

**Comment by Earu** [comment]
Does no work in production.

**Comment by Earu** [comment]
Provide an example of what you're running, I am unable to reproduce this.

**Comment by zxz41** [comment]
It only happens when you say the magic words.

**Comment by zxz41** [comment]
Literally just do this. Boom.
<img src="https://i.imgur.com/yGMeOet.png">

**Comment by Earu** [comment]
Need clarifications, platform, and exact code ran.

**Comment by zxz41** [comment]
You simply send a post message with the `\..` on a folder (can be done within Chrome/Firefox and just renaming the field)
